- debug: var=k8s_pod_cidr



- name: copy flannel yml to config dir
  template:
    src: kube-flannel.yml.j2
    dest: /etc/kubernetes/yml/kube-flannel.yml
  when: (cni) == "flannel"

- name: sed flannel conf
  shell: "sed -i -e 's?10.244.0.0/16?{{ k8s_pod_cidr }}?g'  /etc/kubernetes/yml/kube-flannel.yml"
  when: (cni) == "flannel"
  delegate_to: "{{ groups.master[0]}}"

- name: sed yaml
  shell: sed -i -e 's?quay.io?quay.azk8s.cn?g' -e 's?k8s.gcr.io?gcr.azk8s.cn/google-containers?g' /etc/kubernetes/yml/kube-flannel.yml
  when: (cni) == "flannel"
  delegate_to: "{{ groups.master[0]}}"

- name: apply flannel cni 
  shell: kubectl create -f /etc/kubernetes/yml/kube-flannel.yml
  when: (inventory_hostname) == groups.master[0] and (cni) == "flannel"
  delegate_to: "{{ groups.master[0]}}"

- name: copy calico yml to config dir
  template:
    src: calico-typha.yaml.j2
    dest: /etc/kubernetes/yml/calico-typha.yaml
  when: (cni) == "calico"

- name: sed calico conf
  shell: "sed -i -e 's?192.168.0.0/16?{{ k8s_pod_cidr }}?g'  /etc/kubernetes/yml/calico-typha.yaml"
  when: (cni) == "calico"
  delegate_to: "{{ groups.master[0]}}"

- name: sed yaml
  shell: sed -i -e 's?quay.io?quay.azk8s.cn?g' -e 's?k8s.gcr.io?gcr.azk8s.cn/google-containers?g' -e 's?image: calico?image: dockerhub.azk8s.cn/calico?g' /etc/kubernetes/yml/calico-typha.yaml
  when: (cni) == "calico"
  delegate_to: "{{ groups.master[0]}}"

- name: apply calico cni 
  shell: kubectl create -f /etc/kubernetes/yml/calico-typha.yaml
  when: (inventory_hostname) == groups.master[0] and (cni) == "calico" 
  delegate_to: "{{ groups.master[0]}}"
