---
# to install a mini single node cluster for dev or test environment 
#- hosts: mini
- hosts: "{{ hosts | default('all') | default('localhost')}}"
  gather_facts: smart
  remote_user: root

  roles:
  - init
  - cleanup
